services:
  backend:
    build: .
    ports:
      - "3000:3000"
    networks:
      - mi_red
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

networks:
  mi_red:
    external: true

