version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mibase
    ports:
      - "5432:5432"
    networks:
      - mi_red
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  mi_red:
    external: true
